driver:
  name: vra
  username: "vraadmin"
  password: "Good1bye!"
  tenant: vsphere.local
  base_url: https://vra71.tirefi.re
  verify_ssl: false
  subtenant_id: d0fb4a04-7099-4ba1-a262-b578e129a758

provisioner:
  name: chef_zero
  sudo_command: sudo

verifier:
  name: inspec

transport:
  username: "admini"
  password: admini

platforms:
  - name: ubuntu-14.04
    driver:
      catalog_id: 3f09a0f7-2511-489b-ad6d-2f293d92cd69

suites:
  - name: default
    run_list:
      - recipe[vra_demo::default]
